---
- name: Install IIS Web Server
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: iis_install

- name: Restart host
  win_reboot:
  when: iis_install.reboot_required
